#!/usr/bin/env node
/**
 * Generates db/seed/seed-rituals.sql from the structured data below.
 *
 * Why generate rather than hand-write SQL: ~80 rituals x ~20 fields is easy to
 * get wrong (quoting, column drift) by hand. Editing this file and re-running
 * `node scripts/seed-rituals.mjs` is the supported way to change seed content
 * — do not hand-edit the generated .sql.
 *
 * Every ritual named in PLAN.md §6b appears here exactly once. Scheduling
 * metadata is filled for all of them; runbook prose (agenda/outputs/
 * anti-patterns) is intentionally short — PLAN.md §1 is explicit that the
 * library is an input to scheduling, not the product, and §6c says seed
 * content is expected to be refined over time, not perfect at launch.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "db", "seed", "seed-rituals.sql");

/** @typedef {[jobSlug: string, weight: 1|2|3]} JobTag */

const DEFAULTS = {
  visibility: "public",
  status: "published",
  engagement: "recurring",
  spanWeeks: null,
  defaultCadence: "monthly",
  durationMin: 60,
  prepLeadDays: 2,
  load: "medium",
  participants: "core-team",
  sizeMin: 3,
  sizeMax: 12,
  format: "sync",
  timingHint: null,
  minGapWeeks: null,
  pairsWellWith: [],
  avoidNear: [],
  dependsOn: null,
  facilitatorRole: "Team member (rotating)",
  prepNotes: null,
  materials: [],
  variations: [],
  sourceName: null,
  sourceUrl: null,
  attribution: null,
};

/** @param {string} slug @param {string} title @param {string} category @param {JobTag[]} jobs @param {Partial<typeof DEFAULTS> & {summary:string, purpose:string, agenda:{title:string,minutes?:number}[], outputs:string[], antiPatterns:string[], tags:string[]}} f */
function r(slug, title, category, jobs, f) {
  return { slug, title, category, jobs, ...DEFAULTS, ...f };
}

const RITUALS = [
  // --- A. Design & craft (learning-craft) ---------------------------------
  r("design-crit", "Design Crit", "learning-craft", [["raise-craft", 3]], {
    summary: "Structured critique of in-progress work.",
    purpose: "Catch problems early and raise the craft bar through peer feedback.",
    defaultCadence: "weekly", durationMin: 60, prepLeadDays: 1, load: "medium",
    agenda: [{ title: "Present the work + the question you want feedback on", minutes: 10 }, { title: "Structured critique (round-robin)", minutes: 40 }, { title: "Presenter recaps what they'll act on", minutes: 10 }],
    outputs: ["A short list of concrete next steps for the presenter"],
    antiPatterns: ["Turns into a redesign-by-committee session", "Only senior designers speak"],
    tags: ["critique", "craft"],
  }),
  r("design-review", "Design Review", "learning-craft", [["raise-craft", 2], ["get-aligned", 2]], {
    summary: "A decision-oriented review before work ships, distinct from crit.",
    purpose: "Get explicit sign-off from the people who need to approve the direction.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 3, load: "medium",
    agenda: [{ title: "Walkthrough of the final direction", minutes: 20 }, { title: "Open questions + risks", minutes: 15 }, { title: "Explicit go/no-go", minutes: 10 }],
    outputs: ["A documented decision with named approvers"],
    antiPatterns: ["No one in the room can actually say yes", "Held after the work is already committed"],
    tags: ["review", "decision"],
  }),
  r("portfolio-review", "Portfolio / Work Review", "learning-craft", [["raise-craft", 2], ["learn-faster", 2]], {
    summary: "Look back across a body of work, not a single piece.",
    purpose: "Spot patterns — strengths to double down on, habits to break.",
    defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 5, load: "light",
    agenda: [{ title: "Each person shares 2-3 pieces from the quarter", minutes: 30 }, { title: "Group discussion: what's the pattern?", minutes: 20 }],
    outputs: ["A personal craft-growth note per person"],
    antiPatterns: ["Becomes a performance review by another name"],
    tags: ["craft", "growth"],
  }),
  r("design-system-office-hours", "Design System Office Hours", "learning-craft", [["get-aligned", 2], ["raise-craft", 1]], {
    summary: "Drop-in time to ask design-system questions and propose changes.",
    purpose: "Lower the cost of using and contributing to the system correctly.",
    defaultCadence: "weekly", durationMin: 30, prepLeadDays: 0, load: "light", participants: "extended", sizeMin: 1, sizeMax: 8, format: "hybrid",
    agenda: [{ title: "Open floor for questions", minutes: 20 }, { title: "Log any proposed changes", minutes: 10 }],
    outputs: ["A running list of system change proposals"],
    antiPatterns: ["Nobody shows up because nobody knows it exists"],
    tags: ["design-system"],
  }),
  r("pairing-hour", "Pairing Hour", "learning-craft", [["raise-craft", 2], ["build-cohesion", 1]], {
    summary: "Two people work on the same problem, same screen, same hour.",
    purpose: "Transfer craft and context faster than review comments ever could.",
    defaultCadence: "weekly", durationMin: 60, prepLeadDays: 0, load: "light", sizeMin: 2, sizeMax: 2,
    agenda: [{ title: "Pick a real problem to work on together", minutes: 5 }, { title: "Work it, alternating driver/navigator", minutes: 55 }],
    outputs: ["Shared context on one piece of work"],
    antiPatterns: ["One person drives the whole time"],
    tags: ["craft", "pairing"],
  }),
  r("craft-workshop", "Craft Workshop", "learning-craft", [["learn-faster", 3]], {
    summary: "A hands-on session teaching a specific skill.",
    purpose: "Deliberately grow a skill the team is missing.",
    engagement: "session", defaultCadence: "monthly", durationMin: 90, prepLeadDays: 7, load: "medium", format: "hybrid",
    agenda: [{ title: "Short teaching segment", minutes: 20 }, { title: "Hands-on exercise", minutes: 60 }, { title: "Share-out", minutes: 10 }],
    outputs: ["Practiced skill + shared exercise artifacts"],
    antiPatterns: ["All lecture, no hands-on time"],
    tags: ["skill-building"],
  }),
  r("book-club", "Book / Article Club", "learning-craft", [["learn-faster", 2]], {
    summary: "Read something together and discuss it.",
    purpose: "Build a shared vocabulary and expose the team to outside thinking.",
    defaultCadence: "monthly", durationMin: 45, prepLeadDays: 14, load: "light", format: "hybrid",
    agenda: [{ title: "Discuss key takeaways", minutes: 30 }, { title: "What would we actually try?", minutes: 15 }],
    outputs: ["One experiment the team agrees to try"],
    antiPatterns: ["Nobody actually reads it beforehand"],
    tags: ["learning"],
  }),
  r("sketch-jam", "Sketch Jam", "learning-craft", [["raise-craft", 1], ["explore-new-tech", 1]], {
    summary: "Fast, loose, low-stakes sketching on a shared prompt.",
    purpose: "Generate volume and range before anyone commits to a direction.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 1, load: "light",
    agenda: [{ title: "Prompt + timer", minutes: 20 }, { title: "Pin up and silently review", minutes: 10 }, { title: "Discuss standouts", minutes: 15 }],
    outputs: ["A wall of divergent concepts to draw from"],
    antiPatterns: ["Critiquing quality instead of generating volume"],
    tags: ["ideation"],
  }),
  r("prototype-jam", "Prototype Jam", "learning-craft", [["explore-new-tech", 2], ["raise-craft", 1]], {
    summary: "Build a rough interactive prototype together, fast.",
    purpose: "Answer a question you can't answer from a static mock.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 120, prepLeadDays: 2, load: "medium",
    agenda: [{ title: "Define the question the prototype answers", minutes: 10 }, { title: "Build", minutes: 90 }, { title: "Test on each other", minutes: 20 }],
    outputs: ["A testable prototype", "A clearer answer than a static mock could give"],
    antiPatterns: ["Polishing instead of answering the question"],
    tags: ["prototyping"],
  }),
  r("design-qa-polish-pass", "Design QA / Polish Pass", "learning-craft", [["raise-craft", 2]], {
    summary: "A dedicated pass checking shipped work against the design.",
    purpose: "Catch the gap between what was designed and what shipped.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 2, load: "light", timingHint: "end-of-week", dependsOn: "an implementation to check against",
    agenda: [{ title: "Walk the shipped surface against the spec", minutes: 45 }, { title: "File the gaps", minutes: 15 }],
    outputs: ["A tracked list of polish issues"],
    antiPatterns: ["Done so late it can't be fixed before release"],
    tags: ["quality"],
  }),
  r("accessibility-review", "Accessibility Review", "learning-craft", [["raise-craft", 2], ["better-decisions", 1]], {
    summary: "A focused pass checking a flow against accessibility standards.",
    purpose: "Catch accessibility gaps while they're still cheap to fix.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 3, load: "medium", participants: "extended",
    agenda: [{ title: "Screen-reader + keyboard-only walkthrough", minutes: 40 }, { title: "Log and prioritize findings", minutes: 20 }],
    outputs: ["A prioritized accessibility issue list"],
    antiPatterns: ["Treated as a one-time checkbox instead of a recurring pass"],
    tags: ["accessibility", "quality"],
  }),
  r("content-design-review", "Content Design Review", "learning-craft", [["raise-craft", 2]], {
    summary: "A review focused specifically on the words, not the pixels.",
    purpose: "Catch tone, clarity, and terminology issues before they ship.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 30, prepLeadDays: 1, load: "light",
    agenda: [{ title: "Read the flow end to end, out loud", minutes: 15 }, { title: "Flag terminology and tone issues", minutes: 15 }],
    outputs: ["A list of copy edits"],
    antiPatterns: ["Content reviewed after visual design is locked"],
    tags: ["content-design"],
  }),

  // --- B. UX research & customer exposure (research-customer-exposure) ---
  r("research-readout", "Research Readout", "research-customer-exposure", [["closer-to-customers", 3], ["better-decisions", 1]], {
    summary: "Share what a research effort found, with the people who'll act on it.",
    purpose: "Turn research into decisions instead of a report nobody reads.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 3, load: "medium", participants: "cross-functional",
    agenda: [{ title: "Top findings", minutes: 20 }, { title: "Implications for what we're building", minutes: 15 }, { title: "Who owns which next step", minutes: 10 }],
    outputs: ["Named owners for each implication"],
    antiPatterns: ["A slide deck nobody follows up on"],
    tags: ["research"],
  }),
  r("usability-watch-party", "Usability Test Watch Party", "research-customer-exposure", [["closer-to-customers", 3]], {
    summary: "The team watches a usability session together, live or recorded.",
    purpose: "Build shared, first-hand empathy instead of secondhand summaries.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 1, load: "light", participants: "cross-functional", format: "hybrid",
    agenda: [{ title: "Watch a session together", minutes: 30 }, { title: "Share what stood out", minutes: 15 }],
    outputs: ["A shared, specific memory of a real user"],
    antiPatterns: ["Only researchers attend"],
    tags: ["research"],
  }),
  r("user-exposure-hour", "User Exposure Hour", "research-customer-exposure", [["closer-to-customers", 3]], {
    summary: "Two hours with real users, every six weeks, no exceptions.",
    purpose: "Keep direct customer contact from quietly disappearing off the calendar.",
    defaultCadence: "biweekly", durationMin: 120, prepLeadDays: 5, load: "medium", minGapWeeks: 6,
    agenda: [{ title: "Structured customer conversations", minutes: 90 }, { title: "Debrief together", minutes: 30 }],
    outputs: ["Fresh, first-hand user context for the whole team"],
    antiPatterns: ["Gets cancelled first when the schedule is tight"],
    tags: ["research"],
    sourceName: "Jared Spool", sourceUrl: "https://articles.centercentre.com/exposure_hours/",
    attribution: "Popularized by Jared Spool as a way to keep teams in regular contact with users.",
  }),
  r("support-week", "Customer Support Rotation ('Support Week')", "research-customer-exposure", [["closer-to-customers", 3]], {
    summary: "A team member spends a full week in the support queue.",
    purpose: "First-hand exposure to the sharpest edges of real usage.",
    engagement: "campaign", spanWeeks: 1, defaultCadence: "quarterly", durationMin: null, prepLeadDays: 5, load: "heavy", sizeMin: 1, sizeMax: 1,
    agenda: [{ title: "Shadow support for the week" }, { title: "Log recurring themes" }, { title: "Share back at the end of the week" }],
    outputs: ["A themed list of pain points from real tickets"],
    antiPatterns: ["Rotation exists on paper but nobody actually gets pulled off other work"],
    tags: ["research", "campaign"],
  }),
  r("field-visit", "Field Visit", "research-customer-exposure", [["closer-to-customers", 3]], {
    summary: "Go watch a customer use the product in their own environment.",
    purpose: "See context that a remote interview never surfaces.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 180, prepLeadDays: 14, load: "heavy", sizeMin: 1, sizeMax: 3, format: "hybrid",
    agenda: [{ title: "Observe in context", minutes: 120 }, { title: "Debrief on the way back", minutes: 30 }],
    outputs: ["Field notes with photos/context no remote call captures"],
    antiPatterns: ["Treated as a one-off trip instead of a recurring practice"],
    tags: ["research"],
  }),
  r("research-repo-grooming", "Research Repository Grooming", "research-customer-exposure", [["closer-to-customers", 1], ["get-aligned", 1]], {
    summary: "Tidy and tag the shared research archive.",
    purpose: "Keep past research findable instead of re-discovering it every time.",
    defaultCadence: "monthly", durationMin: 45, prepLeadDays: 1, load: "light", sizeMin: 1, sizeMax: 2,
    agenda: [{ title: "Tag and file new findings", minutes: 30 }, { title: "Archive or merge stale entries", minutes: 15 }],
    outputs: ["An up-to-date, searchable research repository"],
    antiPatterns: ["Repository exists but nobody maintains it"],
    tags: ["research", "operations"],
  }),
  r("assumption-mapping", "Assumption Mapping", "research-customer-exposure", [["better-decisions", 2], ["closer-to-customers", 1]], {
    summary: "Surface and rank the assumptions a plan depends on.",
    purpose: "Find out what you're taking on faith before you build on it.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 2, load: "medium", participants: "cross-functional",
    agenda: [{ title: "List every assumption the plan relies on", minutes: 25 }, { title: "Plot by risk and certainty", minutes: 25 }, { title: "Decide what to test first", minutes: 10 }],
    outputs: ["A ranked list of assumptions to validate"],
    antiPatterns: ["Done once at kickoff and never revisited"],
    tags: ["research", "strategy"],
  }),
  r("journey-map-review", "Journey Map Review", "research-customer-exposure", [["closer-to-customers", 2], ["get-aligned", 1]], {
    summary: "Revisit and update the team's customer journey map.",
    purpose: "Keep the shared model of the customer experience current.",
    defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 3, load: "medium", participants: "cross-functional",
    agenda: [{ title: "Walk the current map", minutes: 20 }, { title: "Update with recent findings", minutes: 30 }],
    outputs: ["An updated, shared journey map"],
    antiPatterns: ["Map is built once and never touched again"],
    tags: ["research"],
  }),
  r("dogfooding-session", "Dogfooding Session", "research-customer-exposure", [["closer-to-customers", 2], ["raise-craft", 1]], {
    summary: "Use your own product like a customer would, on purpose.",
    purpose: "Feel the friction your team has stopped noticing.",
    defaultCadence: "monthly", durationMin: 45, prepLeadDays: 1, load: "light",
    agenda: [{ title: "Complete a real task in the product", minutes: 30 }, { title: "Log friction points", minutes: 15 }],
    outputs: ["A logged list of self-found friction points"],
    antiPatterns: ["Everyone uses the internal/admin version instead of the real product"],
    tags: ["research"],
  }),
  r("insight-of-the-week", "Insight of the Week", "research-customer-exposure", [["closer-to-customers", 1], ["make-work-visible", 1]], {
    summary: "One async post sharing a single user insight.",
    purpose: "Keep a steady drip of customer context flowing without a meeting.",
    format: "async", defaultCadence: "weekly", durationMin: 10, prepLeadDays: 0, load: "light",
    agenda: [{ title: "Post one insight with a quote or clip" }],
    outputs: ["A running, lightweight archive of user insights"],
    antiPatterns: ["Turns into a chore nobody wants to own"],
    tags: ["research", "async"],
  }),
  r("research-study-week", "Research Study Week", "research-customer-exposure", [["run-research-study", 3]], {
    summary: "A focused, one-week push: recruit, run sessions, synthesize, share.",
    purpose: "Get a real answer to a specific question fast, without it dragging for a month.",
    engagement: "campaign", spanWeeks: 1, defaultCadence: "adhoc", durationMin: null, prepLeadDays: 10, load: "heavy", participants: "cross-functional",
    agenda: [{ title: "Recruit + finalize discussion guide" }, { title: "Run sessions" }, { title: "Synthesize" }, { title: "Readout" }],
    outputs: ["A research readout with clear implications"],
    antiPatterns: ["Scope creeps until the week becomes a month"],
    tags: ["research", "campaign"],
    pairsWellWith: ["research-readout"],
  }),

  // --- C. IDEO & human-centred practice (innovation-exploration) ---------
  r("seven-rules-brainstorm", "Brainstorm with the Seven Rules", "innovation-exploration", [["explore-new-tech", 1], ["better-decisions", 1]], {
    summary: "A facilitated brainstorm following IDEO's classic ground rules.",
    purpose: "Generate a wide range of ideas without premature judgment.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 2, load: "medium",
    agenda: [{ title: "Set the seven rules (defer judgment, go for quantity, build on ideas...)", minutes: 5 }, { title: "Generate", minutes: 40 }, { title: "Cluster and vote", minutes: 15 }],
    outputs: ["A clustered set of ideas ranked by the room"],
    antiPatterns: ["Critiquing ideas as they're generated"],
    tags: ["ideation", "ideo"],
    sourceName: "IDEO", sourceUrl: "https://www.ideou.com/blogs/inspiration/7-rules-for-brainstorming",
    attribution: "IDEO's widely-taught brainstorming ground rules.",
  }),
  r("how-might-we", "\"How Might We\" Framing Session", "innovation-exploration", [["better-decisions", 2], ["closer-to-customers", 1]], {
    summary: "Reframe a problem as an open, optimistic question before solving it.",
    purpose: "Avoid jumping to a solution before the problem is well-framed.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 1, load: "light",
    agenda: [{ title: "State the problem/insight", minutes: 10 }, { title: "Generate HMW questions", minutes: 20 }, { title: "Pick the ones worth pursuing", minutes: 15 }],
    outputs: ["A short list of framed HMW questions"],
    antiPatterns: ["Questions are really solutions in disguise"],
    tags: ["ideation", "ideo"],
    sourceName: "IDEO", sourceUrl: "https://www.designkit.org/methods/how-might-we.html",
    attribution: "A core framing technique from IDEO's design-thinking practice.",
  }),
  r("flare-and-focus", "Flare & Focus", "innovation-exploration", [["better-decisions", 2]], {
    summary: "Deliberately alternate between diverging widely and converging sharply.",
    purpose: "Avoid converging too early on the first workable idea.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 90, prepLeadDays: 2, load: "medium",
    agenda: [{ title: "Flare: generate broadly, no filtering", minutes: 40 }, { title: "Focus: converge with explicit criteria", minutes: 40 }],
    outputs: ["A small set of directions chosen against clear criteria"],
    antiPatterns: ["Skipping straight to focus"],
    tags: ["ideation"],
  }),
  r("build-to-think", "Build-to-Think / Prototype-Driven Meeting", "innovation-exploration", [["better-decisions", 2], ["explore-new-tech", 1]], {
    summary: "Bring a rough built artifact into the discussion instead of just talking.",
    purpose: "Make abstract debates concrete faster.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 2, load: "medium",
    agenda: [{ title: "Present the rough build", minutes: 15 }, { title: "React and iterate live", minutes: 35 }],
    outputs: ["A more concrete shared understanding of the direction"],
    antiPatterns: ["The build is too polished to invite real critique"],
    tags: ["prototyping", "ideo"],
  }),
  r("analogous-inspiration-trip", "Analogous Inspiration Trip", "innovation-exploration", [["explore-new-tech", 2], ["learn-faster", 1]], {
    summary: "Study how an unrelated field solves a similar problem.",
    purpose: "Break out of the assumptions your own industry has normalized.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 90, prepLeadDays: 7, load: "medium",
    agenda: [{ title: "Pick an unrelated field with a similar problem", minutes: 10 }, { title: "Research + share findings", minutes: 50 }, { title: "Translate to our context", minutes: 20 }],
    outputs: ["A short list of borrowed ideas worth trying"],
    antiPatterns: ["Interesting but never actually applied"],
    tags: ["ideation", "ideo"],
  }),
  r("design-sprint", "Design Sprint", "innovation-exploration", [["better-decisions", 3], ["run-research-study", 1]], {
    summary: "A five-day push from problem to tested prototype.",
    purpose: "Answer a big, risky question in days instead of months.",
    engagement: "campaign", spanWeeks: 1, defaultCadence: "adhoc", durationMin: null, prepLeadDays: 10, load: "heavy", participants: "cross-functional",
    agenda: [{ title: "Map the problem" }, { title: "Sketch solutions" }, { title: "Decide" }, { title: "Prototype" }, { title: "Test with users" }],
    outputs: ["A tested prototype and a clear go/no-go signal"],
    antiPatterns: ["Run without a real decision-maker in the room"],
    tags: ["campaign", "sprint"],
    sourceName: "Jake Knapp / Google Ventures", sourceUrl: "https://www.gv.com/sprint/",
    attribution: "The Design Sprint format popularized by GV.",
  }),

  // --- D. Innovation & new tech (innovation-exploration) ------------------
  r("ai-new-tech-demo", "AI & New-Tech Demo", "innovation-exploration", [["explore-new-tech", 3]], {
    summary: "Someone shows off a new tool, model, or technique they've tried.",
    purpose: "Keep the team's radar current without everyone researching alone.",
    defaultCadence: "monthly", durationMin: 30, prepLeadDays: 3, load: "light",
    agenda: [{ title: "Live demo", minutes: 15 }, { title: "Discuss where it could apply here", minutes: 15 }],
    outputs: ["Shared awareness of one new tool or technique"],
    antiPatterns: ["Becomes a sales pitch instead of an honest demo"],
    tags: ["ai", "innovation"],
  }),
  r("tech-radar-review", "Tech Radar Review", "innovation-exploration", [["explore-new-tech", 2], ["get-aligned", 1]], {
    summary: "Review and update the team's shared map of tools worth watching.",
    purpose: "Make tool adoption decisions deliberate instead of ad hoc.",
    defaultCadence: "quarterly", durationMin: 45, prepLeadDays: 3, load: "light",
    agenda: [{ title: "Review current radar", minutes: 15 }, { title: "Propose moves (adopt/trial/hold)", minutes: 30 }],
    outputs: ["An updated tech radar"],
    antiPatterns: ["Radar is built once and never revisited"],
    tags: ["innovation", "operations"],
  }),
  r("hack-day", "Hack Day", "innovation-exploration", [["explore-new-tech", 3], ["make-work-visible", 1]], {
    summary: "A day set aside to build whatever you want.",
    purpose: "Give unstructured time for ideas that don't fit the roadmap.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 480, prepLeadDays: 7, load: "heavy", format: "hybrid",
    agenda: [{ title: "Pitch + form groups", minutes: 30 }, { title: "Build", minutes: 390 }, { title: "Share-out", minutes: 60 }],
    outputs: ["A batch of small prototypes, some of which go somewhere"],
    antiPatterns: ["People quietly do their regular work instead"],
    tags: ["innovation"],
  }),
  r("tool-bakeoff", "Tool Bake-Off", "innovation-exploration", [["explore-new-tech", 2], ["better-decisions", 1]], {
    summary: "Compare a few candidate tools head to head on a real task.",
    purpose: "Choose tools based on evidence instead of whoever shouted loudest.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 5, load: "medium",
    agenda: [{ title: "Run the same task through each candidate", minutes: 40 }, { title: "Score against agreed criteria", minutes: 20 }],
    outputs: ["A documented tool decision with criteria"],
    antiPatterns: ["Criteria decided after seeing the results"],
    tags: ["innovation", "decision"],
  }),
  r("lightning-talks", "\"What I Learned\" Lightning Talks", "innovation-exploration", [["learn-faster", 2], ["make-work-visible", 1]], {
    summary: "Short, informal talks on something someone recently learned.",
    purpose: "Spread individual learning across the whole team.",
    defaultCadence: "monthly", durationMin: 30, prepLeadDays: 3, load: "light",
    agenda: [{ title: "2-3 five-minute talks", minutes: 20 }, { title: "Quick Q&A", minutes: 10 }],
    outputs: ["Shared exposure to what individuals are learning"],
    antiPatterns: ["Same one or two people always present"],
    tags: ["learning"],
  }),
  r("ai-prompt-exchange", "AI Prompt Exchange", "innovation-exploration", [["explore-new-tech", 2], ["raise-craft", 1]], {
    summary: "Share prompts, workflows, and AI tricks that actually worked.",
    purpose: "Turn individual AI fluency into a team-wide practice.",
    defaultCadence: "biweekly", durationMin: 30, prepLeadDays: 1, load: "light", format: "hybrid",
    agenda: [{ title: "Show a prompt/workflow that worked well", minutes: 20 }, { title: "Log it somewhere shared", minutes: 10 }],
    outputs: ["A shared, growing library of effective prompts"],
    antiPatterns: ["Only failures get shared, not what worked"],
    tags: ["ai"],
  }),

  // --- E. Alignment & operations (alignment-operations) -------------------
  r("staff-meeting", "Staff Meeting", "alignment-operations", [["get-aligned", 3]], {
    summary: "The team's regular status and alignment meeting.",
    purpose: "Keep everyone working from the same picture of priorities.",
    defaultCadence: "rotation", durationMin: 45, prepLeadDays: 1, load: "medium",
    agenda: [{ title: "Priorities and status", minutes: 20 }, { title: "Blockers and asks", minutes: 15 }, { title: "Announcements", minutes: 10 }],
    outputs: ["A shared, current picture of team priorities"],
    antiPatterns: ["Turns into status theater with no real discussion"],
    tags: ["alignment"],
  }),
  r("roadmap-review", "Roadmap Review", "alignment-operations", [["get-aligned", 3]], {
    summary: "Walk the roadmap and check it still reflects reality.",
    purpose: "Catch roadmap drift before it becomes a surprise.",
    defaultCadence: "rotation", durationMin: 45, prepLeadDays: 2, load: "medium", participants: "cross-functional",
    agenda: [{ title: "Walk current roadmap", minutes: 25 }, { title: "Flag what's changed", minutes: 20 }],
    outputs: ["An updated, shared roadmap"],
    antiPatterns: ["Reviewed so rarely it's always stale"],
    tags: ["alignment", "planning"],
  }),
  r("quarterly-planning", "Quarterly Planning / OKR Setting", "alignment-operations", [["get-aligned", 3], ["better-decisions", 1]], {
    summary: "Set the team's objectives and key results for the quarter.",
    purpose: "Turn strategy into a small number of things the team will actually do.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 180, prepLeadDays: 10, load: "heavy",
    agenda: [{ title: "Review last quarter", minutes: 30 }, { title: "Draft objectives", minutes: 60 }, { title: "Stress-test and finalize", minutes: 60 }],
    outputs: ["A finalized set of OKRs for the quarter"],
    antiPatterns: ["Too many objectives to actually focus on"],
    tags: ["planning", "okr"],
  }),
  r("okr-checkin", "OKR Check-in", "alignment-operations", [["get-aligned", 2]], {
    summary: "A short, regular pulse on progress against the quarter's OKRs.",
    purpose: "Catch drift from the plan while there's still time to correct it.",
    defaultCadence: "biweekly", durationMin: 20, prepLeadDays: 1, load: "light",
    agenda: [{ title: "Confidence rating per key result", minutes: 10 }, { title: "What needs to change", minutes: 10 }],
    outputs: ["An updated confidence score per key result"],
    antiPatterns: ["Confidence scores updated but never acted on"],
    tags: ["okr"],
    dependsOn: "quarterly-planning",
  }),
  r("tgif", "All-Hands / TGIF", "alignment-operations", [["get-aligned", 2], ["build-cohesion", 2]], {
    summary: "A company-wide weekly gathering mixing updates and culture.",
    purpose: "Keep the whole org informed and connected, not just each team.",
    defaultCadence: "weekly", durationMin: 45, prepLeadDays: 2, load: "light", participants: "extended", sizeMin: 20, sizeMax: null,
    agenda: [{ title: "Company updates", minutes: 20 }, { title: "Open Q&A", minutes: 15 }, { title: "Culture moment", minutes: 10 }],
    outputs: ["Company-wide shared context"],
    antiPatterns: ["One-way broadcast with no real Q&A"],
    tags: ["alignment", "culture"],
    sourceName: "Google", sourceUrl: "https://en.wikipedia.org/wiki/Larry_Page#Corporate_culture",
    attribution: "Google's long-running weekly all-hands, TGIF.",
  }),
  r("dory-qa", "Dory Q&A", "alignment-operations", [["get-aligned", 2], ["better-decisions", 1]], {
    summary: "An always-open, votable queue of questions for leadership.",
    purpose: "Surface the questions people actually have, ranked by how many share them.",
    format: "async", defaultCadence: "weekly", durationMin: 20, prepLeadDays: 0, load: "light",
    agenda: [{ title: "Answer the top-voted questions", minutes: 20 }],
    outputs: ["Answered questions visible to everyone who asked or upvoted"],
    antiPatterns: ["Hard questions get quietly skipped"],
    tags: ["alignment", "transparency"],
    sourceName: "Coda", sourceUrl: "https://coda.io/gallery/rituals-of-great-teams",
    attribution: "Coda's internal Q&A tool/ritual, referenced in Shishir Mehrotra's 'Rituals of Great Teams'.",
  }),
  r("pulse", "Pulse", "alignment-operations", [["get-aligned", 1], ["build-cohesion", 2]], {
    summary: "A short, regular check on team sentiment and morale.",
    purpose: "Catch morale problems while they're still small.",
    format: "async", defaultCadence: "biweekly", durationMin: 5, prepLeadDays: 0, load: "light",
    agenda: [{ title: "A short anonymous pulse survey" }],
    outputs: ["A trend line on team sentiment"],
    antiPatterns: ["Results collected but never shared back or acted on"],
    tags: ["culture", "async"],
    sourceName: "Coda", sourceUrl: "https://coda.io/gallery/rituals-of-great-teams",
    attribution: "Coda's internal sentiment-tracking ritual, referenced in Shishir Mehrotra's 'Rituals of Great Teams'.",
  }),
  r("v2mom", "V2MOM", "alignment-operations", [["get-aligned", 3], ["better-decisions", 1]], {
    summary: "A framework aligning Vision, Values, Methods, Obstacles, Measures.",
    purpose: "Cascade strategy from company to team in a consistent shape.",
    engagement: "session", defaultCadence: "annual", durationMin: 120, prepLeadDays: 10, load: "heavy",
    agenda: [{ title: "Draft each of the five sections", minutes: 90 }, { title: "Align with adjacent teams", minutes: 30 }],
    outputs: ["A published V2MOM for the team"],
    antiPatterns: ["Written once a year and never referenced again"],
    tags: ["planning", "strategy"],
    sourceName: "Salesforce", sourceUrl: "https://www.salesforce.com/news/stories/how-we-align-our-entire-company-around-a-common-set-of-priorities/",
    attribution: "Salesforce's company-wide alignment framework.",
  }),
  r("standup", "Standup / Async Check-in", "alignment-operations", [["get-aligned", 2]], {
    summary: "A brief, frequent sync on what's happening right now.",
    purpose: "Surface blockers fast, in either live or async form.",
    defaultCadence: "weekly", durationMin: 10, prepLeadDays: 0, load: "light",
    agenda: [{ title: "What I did, what's next, what's blocking me" }],
    outputs: ["Blockers surfaced within a day of appearing"],
    antiPatterns: ["Turns into a full status meeting"],
    tags: ["alignment"],
  }),
  r("weekly-snippets", "Weekly Written Update ('Snippets')", "alignment-operations", [["get-aligned", 2], ["make-work-visible", 1]], {
    summary: "A short written update on what you did this week.",
    purpose: "Make individual work visible without a meeting.",
    format: "async", defaultCadence: "weekly", durationMin: 10, prepLeadDays: 0, load: "light",
    agenda: [{ title: "Write 3-5 bullet points on the week" }],
    outputs: ["A searchable written record of what happened, when"],
    antiPatterns: ["Written but nobody reads them"],
    tags: ["alignment", "async"],
  }),
  r("no-meeting-week", "No-Meeting Day / Week", "alignment-operations", [["raise-craft", 1], ["get-aligned", 1]], {
    summary: "A protected stretch with no meetings at all.",
    purpose: "Give the team real, uninterrupted focus time — a scheduling ritual in its own right.",
    engagement: "campaign", spanWeeks: 1, defaultCadence: "monthly", durationMin: null, prepLeadDays: 3, load: "light",
    agenda: [{ title: "Block the calendar in advance" }, { title: "Hold the line — no exceptions meetings" }],
    outputs: ["A real stretch of protected focus time"],
    antiPatterns: ["Quietly filled back in with 'quick syncs'"],
    tags: ["operations", "focus"],
  }),

  // --- F. Showcase & storytelling (showcase-storytelling) -----------------
  r("product-showcase", "Product Showcase (Low-Key)", "showcase-storytelling", [["make-work-visible", 3]], {
    summary: "An informal show-and-tell of recent work.",
    purpose: "Keep the team's output visible without turning it into a big production.",
    defaultCadence: "rotation", durationMin: 30, prepLeadDays: 2, load: "light", participants: "extended",
    agenda: [{ title: "2-3 people show recent work", minutes: 20 }, { title: "Quick reactions", minutes: 10 }],
    outputs: ["Shared visibility into recent output"],
    antiPatterns: ["Only 'finished and polished' work gets shown"],
    tags: ["showcase"],
  }),
  r("demo-day", "Demo Day / Ship Review", "showcase-storytelling", [["ship-launch-well", 2], ["make-work-visible", 2]], {
    summary: "A more formal review of what's about to ship or just shipped.",
    purpose: "Give a launch a clear, visible moment instead of quietly going live.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 5, load: "medium", participants: "cross-functional",
    agenda: [{ title: "Demo the shipping work", minutes: 25 }, { title: "Q&A", minutes: 15 }],
    outputs: ["Shared awareness of what's about to go live"],
    antiPatterns: ["Held after it's already shipped, so feedback is moot"],
    tags: ["showcase", "launch"],
  }),
  r("team-spotlight", "Team Spotlight", "showcase-storytelling", [["build-cohesion", 3], ["make-work-visible", 1]], {
    summary: "A short segment highlighting one person's work or story.",
    purpose: "Give individual contributors visible, specific recognition.",
    defaultCadence: "rotation", durationMin: 15, prepLeadDays: 3, load: "light",
    agenda: [{ title: "One person shares their work or story", minutes: 10 }, { title: "Team reactions", minutes: 5 }],
    outputs: ["Visible, specific recognition for one person"],
    antiPatterns: ["Always the same few people get spotlighted"],
    tags: ["culture", "recognition"],
  }),
  r("launch-story", "Launch Story / Release Notes Ritual", "showcase-storytelling", [["make-work-visible", 2], ["ship-launch-well", 1]], {
    summary: "Write up the story of a launch, not just the changelog.",
    purpose: "Turn a shipped feature into a shareable narrative.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 30, prepLeadDays: 1, load: "light", format: "async", dependsOn: "a shipped launch",
    agenda: [{ title: "Draft the story: problem, approach, outcome" }],
    outputs: ["A shareable launch write-up"],
    antiPatterns: ["Reduced to a bare bullet-point changelog"],
    tags: ["showcase", "storytelling"],
  }),
  r("internal-newsletter", "Internal Newsletter", "showcase-storytelling", [["make-work-visible", 2], ["get-aligned", 1]], {
    summary: "A regular written roundup of what the team shipped and learned.",
    purpose: "Give stakeholders a single, skimmable source of truth.",
    format: "async", defaultCadence: "monthly", durationMin: 45, prepLeadDays: 2, load: "light", sizeMin: 1, sizeMax: 1,
    agenda: [{ title: "Compile shipped work, learnings, and upcoming plans" }],
    outputs: ["A published internal newsletter"],
    antiPatterns: ["Falls to one person who eventually burns out on it"],
    tags: ["showcase", "communication"],
  }),

  // --- G. Decision making (decision-making) --------------------------------
  r("spade", "SPADE", "decision-making", [["better-decisions", 3]], {
    summary: "A structured framework for making a hard decision explicit.",
    purpose: "Make the setting, people, alternatives, decision, and explanation visible.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 3, load: "medium",
    agenda: [{ title: "Setting + People + Alternatives", minutes: 20 }, { title: "Decide", minutes: 15 }, { title: "Explain in writing", minutes: 15 }],
    outputs: ["A documented SPADE decision"],
    antiPatterns: ["Alternatives listed but never seriously considered"],
    tags: ["decision"],
    sourceName: "Gokul Rajaram", sourceUrl: "https://www.coda.io/@gokulrajaram/spade",
    attribution: "Gokul Rajaram's SPADE framework, used at Google, Square, and elsewhere.",
  }),
  r("daci", "DACI", "decision-making", [["better-decisions", 2], ["get-aligned", 1]], {
    summary: "Assign Driver, Approver, Contributors, and Informed for a decision.",
    purpose: "Make decision ownership explicit before the meeting, not after.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 30, prepLeadDays: 2, load: "light",
    agenda: [{ title: "Assign the four roles", minutes: 10 }, { title: "Driver runs the actual decision", minutes: 20 }],
    outputs: ["A decision with explicit, named roles"],
    antiPatterns: ["Roles assigned but the Approver isn't actually in the room"],
    tags: ["decision"],
  }),
  r("six-pager-silent-read", "Six-Pager Silent Read", "decision-making", [["better-decisions", 2], ["get-aligned", 1]], {
    summary: "Read a written narrative document silently at the start of the meeting.",
    purpose: "Force clear writing and a shared starting point before discussion.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 3, load: "medium",
    agenda: [{ title: "Silent read", minutes: 20 }, { title: "Discussion", minutes: 40 }],
    outputs: ["A discussion grounded in a shared, detailed document"],
    antiPatterns: ["People skim instead of reading fully"],
    tags: ["decision", "writing"],
    sourceName: "Amazon", sourceUrl: "https://www.aboutamazon.com/news/workplace/how-jeff-bezos-turned-narrative-into-a-management-tool",
    attribution: "Amazon's narrative-memo meeting format.",
  }),
  r("pre-mortem", "Pre-Mortem", "decision-making", [["better-decisions", 3]], {
    summary: "Imagine the project has already failed, then work out why.",
    purpose: "Surface risks while there's still time to address them.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 2, load: "medium", participants: "cross-functional",
    agenda: [{ title: "Imagine failure and list reasons", minutes: 20 }, { title: "Rank by likelihood and impact", minutes: 15 }, { title: "Mitigate the top risks", minutes: 10 }],
    outputs: ["A ranked risk list with mitigations"],
    antiPatterns: ["Run once and the risks are never revisited"],
    tags: ["decision", "risk"],
  }),
  r("disagree-and-commit", "Disagree-and-Commit Checkpoint", "decision-making", [["better-decisions", 2], ["get-aligned", 1]], {
    summary: "An explicit moment to voice disagreement, then commit as a team.",
    purpose: "Get disagreement on the table before it becomes quiet resistance later.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 20, prepLeadDays: 0, load: "light", dependsOn: "a decision already on the table",
    agenda: [{ title: "Explicitly ask: who disagrees, and why?", minutes: 10 }, { title: "Confirm commitment", minutes: 10 }],
    outputs: ["Voiced disagreement, followed by real commitment"],
    antiPatterns: ["Skipped because it feels confrontational"],
    tags: ["decision"],
  }),
  r("decision-log-review", "Decision Log Review", "decision-making", [["better-decisions", 2], ["get-aligned", 1]], {
    summary: "Revisit past decisions to see if they still hold.",
    purpose: "Catch decisions that quietly went stale.",
    defaultCadence: "quarterly", durationMin: 30, prepLeadDays: 2, load: "light",
    agenda: [{ title: "Review the decision log", minutes: 20 }, { title: "Flag anything worth revisiting", minutes: 10 }],
    outputs: ["An up-to-date decision log"],
    antiPatterns: ["No decision log exists to review"],
    tags: ["decision", "operations"],
  }),
  r("rapids", "Rapids", "decision-making", [["better-decisions", 2]], {
    summary: "A lightweight framework for fast, async decision-making.",
    purpose: "Keep small decisions from clogging up synchronous meeting time.",
    format: "async", defaultCadence: "adhoc", durationMin: 15, prepLeadDays: 1, load: "light",
    agenda: [{ title: "Propose the decision in writing" }, { title: "Async input window" }, { title: "Decide and record" }],
    outputs: ["A fast, recorded async decision"],
    antiPatterns: ["Used for decisions that actually need real-time debate"],
    tags: ["decision", "async"],
    sourceName: "Coinbase", sourceUrl: "https://www.coinbase.com/blog/rapid-decision-making-at-coinbase",
    attribution: "Coinbase's async decision-making framework, Rapids.",
  }),

  // --- H. People & culture (people-culture) --------------------------------
  r("kudos-round", "Kudos / Shout-Outs Round", "people-culture", [["build-cohesion", 3]], {
    summary: "A quick round of public recognition for each other's work.",
    purpose: "Make appreciation a habit instead of an afterthought.",
    defaultCadence: "weekly", durationMin: 10, prepLeadDays: 0, load: "light",
    agenda: [{ title: "Anyone shouts out someone else", minutes: 10 }],
    outputs: ["Public, specific recognition"],
    antiPatterns: ["Same two people always get shouted out"],
    tags: ["culture", "recognition"],
  }),
  r("fail-faire", "Fail Faire", "people-culture", [["build-cohesion", 2], ["learn-faster", 2]], {
    summary: "Openly share something that didn't work, and what you learned.",
    purpose: "Make failure discussable instead of hidden.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 45, prepLeadDays: 5, load: "medium",
    agenda: [{ title: "2-3 people share a failure and the lesson", minutes: 30 }, { title: "Open discussion", minutes: 15 }],
    outputs: ["Normalized, visible discussion of failure"],
    antiPatterns: ["Only safe, low-stakes 'failures' get shared"],
    tags: ["culture", "learning"],
  }),
  r("working-with-me", "Personal User Manual / 'Working With Me'", "people-culture", [["build-cohesion", 2], ["onboard-well", 2]], {
    summary: "Each person writes a short guide to how they like to work.",
    purpose: "Reduce friction from unstated working-style differences.",
    engagement: "session", defaultCadence: "annual", durationMin: 30, prepLeadDays: 3, load: "light", format: "async",
    agenda: [{ title: "Write your own manual" }, { title: "Share with the team" }],
    outputs: ["A published personal working-style guide"],
    antiPatterns: ["Written once and never updated as roles change"],
    tags: ["culture", "onboarding"],
  }),
  r("manager-1-1", "Manager 1:1", "people-culture", [["build-cohesion", 2], ["get-aligned", 2], ["learn-faster", 1]], {
    summary: "A regular, private conversation between a manager and their direct report.",
    purpose: "Give every direct report dedicated time with their manager — not just group updates.",
    defaultCadence: "weekly", durationMin: 30, prepLeadDays: 0, load: "light", sizeMin: 2, sizeMax: 2,
    facilitatorRole: "Direct report (sets the agenda)",
    agenda: [{ title: "Whatever's on the report's mind first", minutes: 10 }, { title: "Status and blockers", minutes: 10 }, { title: "Feedback, both directions", minutes: 10 }],
    outputs: ["Blockers surfaced and unblocked before they compound", "Feedback exchanged in both directions"],
    antiPatterns: ["Manager does all the talking", "Turns into a pure status update, crowding out anything personal", "First meeting cancelled when the calendar gets tight"],
    tags: ["1:1", "management"],
  }),
  r("random-coffee", "Random Coffee Pairing", "people-culture", [["build-cohesion", 3]], {
    summary: "Randomly paired 1:1 chats with no work agenda.",
    purpose: "Build relationships across the team that wouldn't happen otherwise.",
    defaultCadence: "biweekly", durationMin: 30, prepLeadDays: 0, load: "light", sizeMin: 2, sizeMax: 2, format: "hybrid",
    agenda: [{ title: "Just talk — no work agenda required" }],
    outputs: ["A cross-team relationship that wouldn't otherwise form"],
    antiPatterns: ["Turns into a work status meeting anyway"],
    tags: ["culture"],
  }),
  r("onboarding-programme", "New-Hire Onboarding Programme", "people-culture", [["onboard-well", 3]], {
    summary: "A structured multi-week ramp for new team members.",
    purpose: "Get new hires productive and connected without leaving it to chance.",
    engagement: "series", spanWeeks: 6, defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 7, load: "medium", sizeMin: 1, sizeMax: 1,
    agenda: [{ title: "Week 1: context and access" }, { title: "Weeks 2-4: guided first tasks with a buddy" }, { title: "Weeks 5-6: first independent contribution" }],
    outputs: ["A new hire who's contributed independently by week six"],
    antiPatterns: ["Same generic plan regardless of role or experience level"],
    tags: ["onboarding", "series"],
    pairsWellWith: ["working-with-me"],
  }),
  r("work-anniversaries", "Work Anniversaries & Birthdays", "people-culture", [["build-cohesion", 2]], {
    summary: "Acknowledge personal milestones as a team.",
    purpose: "Small, low-cost signals that people are seen as people.",
    defaultCadence: "monthly", durationMin: 10, prepLeadDays: 1, load: "light",
    agenda: [{ title: "Acknowledge the milestone" }],
    outputs: ["A small, consistent moment of recognition"],
    antiPatterns: ["Forgotten until someone points it out"],
    tags: ["culture", "recognition"],
  }),
  r("career-growth-checkin", "Career Growth Check-in", "people-culture", [["build-cohesion", 1], ["learn-faster", 2]], {
    summary: "A regular 1:1 conversation focused only on growth, not status.",
    purpose: "Keep career development from being crowded out by day-to-day work talk.",
    defaultCadence: "quarterly", durationMin: 30, prepLeadDays: 3, load: "light", sizeMin: 2, sizeMax: 2,
    agenda: [{ title: "Reflect on growth since last check-in", minutes: 15 }, { title: "Set focus for next period", minutes: 15 }],
    outputs: ["An updated, personal growth plan"],
    antiPatterns: ["Collapses into a regular status 1:1"],
    tags: ["growth"],
  }),
  r("mentorship-pairing", "Mentorship Pairing", "people-culture", [["learn-faster", 2], ["build-cohesion", 2]], {
    summary: "A longer-term pairing between a mentor and mentee.",
    purpose: "Give growth a dedicated, ongoing relationship instead of ad hoc advice.",
    engagement: "campaign", spanWeeks: 52, defaultCadence: "biweekly", durationMin: 30, prepLeadDays: 3, load: "light", sizeMin: 2, sizeMax: 2,
    agenda: [{ title: "Regular check-in, mentee sets the agenda" }],
    outputs: ["A sustained, trusted mentoring relationship"],
    antiPatterns: ["Paired once with no structure or expectations set"],
    tags: ["growth", "campaign"],
  }),
  r("cupcake", "Cupcake", "people-culture", [["build-cohesion", 2]], {
    summary: "A DoorDash culture ritual, deliberately given a memorable, non-corporate name.",
    purpose: "Make a recurring practice easy to remember and refer to by name.",
    defaultCadence: "monthly", durationMin: 30, prepLeadDays: 2, load: "light",
    agenda: [{ title: "Team-specific — named rituals are meant to be shaped locally" }],
    outputs: ["A team practice people actually remember and reference"],
    antiPatterns: ["Adopted by name only, without the substance behind it"],
    tags: ["culture"],
    sourceName: "DoorDash", sourceUrl: "https://coda.io/gallery/rituals-of-great-teams",
    attribution: "Referenced in Shishir Mehrotra's 'Rituals of Great Teams' as an example of a memorably-named team ritual.",
  }),
  r("spin-the-wheel", "Spin the Wheel", "people-culture", [["build-cohesion", 2]], {
    summary: "A Stripe culture ritual using a randomizing mechanic to pick who does what.",
    purpose: "Add a bit of fun/fairness to an otherwise mundane rotation decision.",
    defaultCadence: "monthly", durationMin: 15, prepLeadDays: 0, load: "light",
    agenda: [{ title: "Spin to decide (topic, presenter, task owner, etc.)" }],
    outputs: ["A fairly and memorably chosen rotation"],
    antiPatterns: ["The randomizer is quietly rigged"],
    tags: ["culture"],
    sourceName: "Stripe", sourceUrl: "https://coda.io/gallery/rituals-of-great-teams",
    attribution: "Referenced in Shishir Mehrotra's 'Rituals of Great Teams' as an example of a memorably-named team ritual.",
  }),
  r("hiring-call", "Hiring Call", "people-culture", [["build-cohesion", 1], ["get-aligned", 1]], {
    summary: "A dedicated call to discuss a candidate right after interviews.",
    purpose: "Make hiring decisions quickly, while impressions are fresh.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 30, prepLeadDays: 0, load: "medium", dependsOn: "a completed interview loop",
    agenda: [{ title: "Each interviewer shares their read", minutes: 15 }, { title: "Decide", minutes: 15 }],
    outputs: ["A timely hiring decision"],
    antiPatterns: ["Delayed so long the candidate accepts elsewhere"],
    tags: ["hiring"],
    sourceName: "Gusto", sourceUrl: "https://coda.io/gallery/rituals-of-great-teams",
    attribution: "Referenced in Shishir Mehrotra's 'Rituals of Great Teams'.",
  }),
  r("weekly-wins", "Weekly Wins / Gratitude Round", "people-culture", [["build-cohesion", 2]], {
    summary: "End the week naming something that went well.",
    purpose: "Close the week on what worked, not just what's left undone.",
    defaultCadence: "weekly", durationMin: 10, prepLeadDays: 0, load: "light", timingHint: "end-of-week",
    agenda: [{ title: "Everyone names one win from the week" }],
    outputs: ["A weekly note of what went well"],
    antiPatterns: ["Becomes rote — same generic answer every week"],
    tags: ["culture"],
  }),

  // --- I. Reflection & renewal (reflection-renewal) ------------------------
  r("retro", "Retro", "reflection-renewal", [["get-aligned", 2], ["learn-faster", 1]], {
    summary: "The team reflects on a period of work and agrees on changes.",
    purpose: "Turn recent experience into concrete process improvements.",
    defaultCadence: "biweekly", durationMin: 60, prepLeadDays: 1, load: "medium",
    agenda: [{ title: "Gather data: what happened", minutes: 15 }, { title: "Generate insights", minutes: 25 }, { title: "Decide what to change", minutes: 20 }],
    outputs: ["A short list of concrete process changes"],
    antiPatterns: ["Same issues raised every time with no follow-through"],
    variations: [{ name: "Starfish", description: "Keep doing / less of / more of / stop / start" }, { name: "Sailboat", description: "Wind, anchors, rocks, island" }, { name: "4Ls", description: "Liked, learned, lacked, longed for" }],
    tags: ["reflection"],
    sourceName: "Derby & Larsen", sourceUrl: "https://www.agilealliance.org/glossary/heartbeat-retro/",
    attribution: "Format popularized by Esther Derby and Diana Larsen's Agile Retrospectives.",
  }),
  r("post-launch-retro", "Post-Launch Retro", "reflection-renewal", [["ship-launch-well", 3], ["learn-faster", 1]], {
    summary: "A retro specifically about how a launch went.",
    purpose: "Capture launch-specific lessons while they're still fresh.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 45, prepLeadDays: 1, load: "medium", participants: "cross-functional", dependsOn: "a completed launch",
    agenda: [{ title: "What went well / what didn't, launch-specific", minutes: 30 }, { title: "What to change next time", minutes: 15 }],
    outputs: ["Launch-specific lessons captured before they're forgotten"],
    antiPatterns: ["Skipped when the launch goes smoothly"],
    tags: ["reflection", "launch"],
  }),
  r("working-agreement-refresh", "Working Agreement Refresh", "reflection-renewal", [["get-aligned", 2], ["build-cohesion", 1]], {
    summary: "Revisit and update the team's explicit working agreements.",
    purpose: "Keep team norms matched to how the team actually works now.",
    defaultCadence: "quarterly", durationMin: 45, prepLeadDays: 3, load: "light",
    agenda: [{ title: "Review current agreements", minutes: 20 }, { title: "Propose changes", minutes: 25 }],
    outputs: ["An updated working agreement"],
    antiPatterns: ["Written once and never revisited as the team changes"],
    tags: ["reflection", "operations"],
  }),
  r("team-offsite", "Team Offsite", "reflection-renewal", [["build-cohesion", 3], ["get-aligned", 1]], {
    summary: "A day or more away from the daily routine, together.",
    purpose: "Create space for the deeper conversations daily work crowds out.",
    engagement: "session", defaultCadence: "annual", durationMin: 480, prepLeadDays: 21, load: "heavy",
    agenda: [{ title: "Strategy/vision discussion" }, { title: "Team-building activity" }, { title: "Social time" }],
    outputs: ["Renewed alignment and relationships"],
    antiPatterns: ["Agenda so packed there's no unstructured time"],
    tags: ["reflection", "culture"],
  }),
  r("reset", "Reset", "reflection-renewal", [["reset-after-hard-stretch", 3]], {
    summary: "A deliberate pause and recalibration after a hard stretch.",
    purpose: "Recover on purpose instead of just moving on to the next thing.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 2, load: "light",
    agenda: [{ title: "Name what the hard stretch cost", minutes: 20 }, { title: "Decide what recovery looks like", minutes: 20 }],
    outputs: ["An explicit, shared permission to recover"],
    antiPatterns: ["Skipped because the next deadline is already looming"],
    tags: ["reflection", "wellbeing"],
    sourceName: "Thrive / Arianna Huffington", sourceUrl: "https://www.lennysnewsletter.com/p/the-rituals-of-great-teams-shishir",
    attribution: "Referenced in Shishir Mehrotra's research on team rituals.",
  }),
  r("quarterly-ritual-audit", "Quarterly Ritual Audit", "reflection-renewal", [["get-aligned", 2], ["reset-after-hard-stretch", 1]], {
    summary: "Step back and assess whether the team's rituals are actually working.",
    purpose: "Catch rituals that have gone stale before they quietly die or calcify.",
    defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 5, load: "medium",
    agenda: [{ title: "Score the team's process health across key pillars", minutes: 30 }, { title: "Decide what to add, cut, or change", minutes: 30 }],
    outputs: ["A concrete list of ritual changes for next quarter"],
    antiPatterns: ["Findings aren't fed back into the actual schedule"],
    tags: ["reflection", "meta"],
    pairsWellWith: ["working-agreement-refresh"],
  }),
  r("calendar-audit", "Calendar Audit / Meeting Cleanse", "reflection-renewal", [["get-aligned", 2], ["raise-craft", 1]], {
    summary: "Review every recurring meeting and decide if it still earns its slot.",
    purpose: "Fight meeting creep before it eats the whole calendar.",
    defaultCadence: "quarterly", durationMin: 45, prepLeadDays: 2, load: "light",
    agenda: [{ title: "List every recurring meeting", minutes: 15 }, { title: "Keep, cut, or change each one", minutes: 30 }],
    outputs: ["A trimmed, intentional recurring-meeting list"],
    antiPatterns: ["Meetings get cut, then quietly re-added within a month"],
    tags: ["operations", "meta"],
  }),

  // --- J. Outside voices (outside-voices) ----------------------------------
  r("guest-speaker-series", "Guest Speaker Series", "outside-voices", [["learn-faster", 2], ["explore-new-tech", 1]], {
    summary: "A recurring slot for an outside speaker.",
    purpose: "Bring in perspective the team doesn't have internally.",
    engagement: "series", spanWeeks: 12, defaultCadence: "monthly", durationMin: 45, prepLeadDays: 14, load: "medium", participants: "guests",
    agenda: [{ title: "Talk", minutes: 30 }, { title: "Q&A", minutes: 15 }],
    outputs: ["Outside perspective shared with the whole team"],
    antiPatterns: ["Speakers booked but nobody preps good questions"],
    tags: ["guests"],
  }),
  r("cross-functional-exchange", "Cross-Functional Exchange", "outside-voices", [["closer-to-customers", 1], ["build-cohesion", 1]], {
    summary: "Swap seats with another function for a session.",
    purpose: "Build empathy and shared context across disciplines.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 5, load: "medium", participants: "cross-functional",
    agenda: [{ title: "Shadow or swap for the session", minutes: 45 }, { title: "Debrief what surprised you", minutes: 15 }],
    outputs: ["Concrete, shared cross-functional context"],
    antiPatterns: ["Treated as a novelty instead of a repeatable practice"],
    tags: ["guests", "collaboration"],
  }),
  r("external-crit", "External Crit With Another Company's Team", "outside-voices", [["raise-craft", 2]], {
    summary: "Trade critique with a design team from outside the company.",
    purpose: "Get feedback free of internal politics and blind spots.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 10, load: "medium", participants: "guests",
    agenda: [{ title: "Present work to the external team", minutes: 20 }, { title: "Trade critique both ways", minutes: 40 }],
    outputs: ["Outside-perspective feedback on real work"],
    antiPatterns: ["One-sided — only your work gets critiqued"],
    tags: ["guests", "craft"],
  }),
  r("conference-watch-party", "Conference / Talk Watch Party", "outside-voices", [["learn-faster", 1], ["build-cohesion", 1]], {
    summary: "Watch an industry talk together and discuss it.",
    purpose: "Share the cost of staying current with the field.",
    engagement: "session", defaultCadence: "adhoc", durationMin: 60, prepLeadDays: 2, load: "light", format: "hybrid",
    agenda: [{ title: "Watch together", minutes: 40 }, { title: "Discuss takeaways", minutes: 20 }],
    outputs: ["Shared exposure to outside thinking"],
    antiPatterns: ["Watched individually beforehand, discussion falls flat"],
    tags: ["learning", "guests"],
  }),
  r("customer-advisory-session", "Customer Advisory Session", "outside-voices", [["closer-to-customers", 3]], {
    summary: "A structured session with a small panel of customers.",
    purpose: "Get direct, ongoing input from customers who have real stakes.",
    engagement: "session", defaultCadence: "quarterly", durationMin: 60, prepLeadDays: 14, load: "medium", participants: "guests",
    agenda: [{ title: "Present roadmap direction", minutes: 20 }, { title: "Open discussion", minutes: 40 }],
    outputs: ["Direct customer input on direction, not just features"],
    antiPatterns: ["Panel hears the same pitch every time with no real listening"],
    tags: ["research", "guests"],
  }),
];

function esc(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return `'${String(v).replace(/'/g, "''")}'`;
}
const json = (v) => esc(JSON.stringify(v ?? []));

const COLUMNS = [
  "slug", "title", "summary", "purpose",
  "visibility", "status", "engagement", "span_weeks", "default_cadence",
  "duration_min", "prep_lead_days", "load", "participants", "size_min", "size_max",
  "format", "timing_hint", "min_gap_weeks", "pairs_well_with", "avoid_near", "depends_on",
  "facilitator_role", "prep_notes", "agenda", "outputs", "materials", "anti_patterns", "variations",
  "tags", "source_name", "source_url", "attribution", "source_verified", "category_id",
];

let sql = `-- Generated by scripts/seed-rituals.mjs — do not hand-edit.\n-- Run: node scripts/seed-rituals.mjs\n\n`;

for (const rr of RITUALS) {
  const values = [
    esc(rr.slug), esc(rr.title), esc(rr.summary), esc(rr.purpose),
    esc(rr.visibility), esc(rr.status), esc(rr.engagement), esc(rr.spanWeeks), esc(rr.defaultCadence),
    esc(rr.durationMin), esc(rr.prepLeadDays), esc(rr.load), esc(rr.participants), esc(rr.sizeMin), esc(rr.sizeMax),
    esc(rr.format), esc(rr.timingHint), esc(rr.minGapWeeks), json(rr.pairsWellWith), json(rr.avoidNear), esc(rr.dependsOn),
    esc(rr.facilitatorRole), esc(rr.prepNotes), json(rr.agenda), json(rr.outputs), json(rr.materials), json(rr.antiPatterns), json(rr.variations),
    json(rr.tags), esc(rr.sourceName), esc(rr.sourceUrl), esc(rr.attribution), "0",
    `(SELECT id FROM categories WHERE slug = ${esc(rr.category)})`,
  ];
  sql += `INSERT INTO rituals (${COLUMNS.join(", ")}) VALUES (${values.join(", ")});\n`;
}

sql += `\n-- Job tags\n`;
for (const rr of RITUALS) {
  for (const [jobSlug, weight] of rr.jobs) {
    sql += `INSERT INTO ritual_jobs (ritual_id, job_id, weight) SELECT (SELECT id FROM rituals WHERE slug = ${esc(rr.slug)}), (SELECT id FROM jobs WHERE slug = ${esc(jobSlug)}), ${weight};\n`;
  }
}

writeFileSync(OUT, sql);
console.log(`Wrote ${RITUALS.length} rituals -> ${OUT}`);
